### PR TITLE
Level 2 BLAS + Some fixes

### PR DESCRIPTION
**Pull request by Ki11erRabbit**
Here are the changes that I made to get Level 2 BLAS bindings in place as well as a fix that causes the current level 1 bindings to not compile.
Before merging, I would like to know if I should have the high level bindings be qualified or should I put the qualification in the function name:
Example:
```koka
pub inline fun blas/blasmatrix/general/rank-one-update( m : blasmatrix, v1 : blasvector, v2 : blasvector, alpha : float64 = 1.0, row-major : bool = True ) : blasmatrix
  blas/ger( alpha, m.copy, v1, v2, row-major )

pub inline fun blas/blasmatrix/symmetric/rank-one-update( m : blasmatrix, v : blasvector, upper-triangular : bool, alpha : float64 = 1.0, row-major : bool = True ) : blasmatrix
  blas/syr( alpha, m.copy, v, row-major, upper = upper-triangular )
```
I am not sure if the compiler might get these confused with each other or other ones as well.

### CODE REVIEW

**Comment by Ki11erRabbit** [comment]
Also if I uncomment the tests for the raw BLAS Level 2 bindings it causes a compiler error that I am not sure how to fix.

**Comment by TimWhiting** [comment]
Instead of prefixing everything with `blas/blasmatrix/` just put those files in a folder / file with the appropriate path, and then reexport from the `linalg` or whatever using `pub import blas/blasmatrix`. This way they can be referred to directly, but don't have a long name in the file. 

And then instead of `linalg-blas.kk` I would just put it into a blas folder `blas/linalg`.

Also, as long as the non-optional arguments all have different types, leave them with the same name (overloaded), but with different local prefixes (i.e. `symmetric/rank-one-update`, and `generic/rank-one-update`).

The advantage of naming things consistenly really applies when writing implicits which use names to find the appropriate function. Though `rank-one-update` might not be used in connection with implicits, the fact of implicits and overloading in Koka is that naming via local prefixes should be preferred over qualifying in the function name. This will keep Koka more consistent instead of sometimes qualifying via a prefix and sometimes in the function name. 

There are of course cases where two functions have the same parameters, and would always need to be qualified, where a qualified name might make more sense. However, I believe it should only be done if the qualified name makes the behavior of the function more clear or distinguished.

**Comment by Ki11erRabbit** [comment]
Makes sense. I wasn't too happy with the structure myself. That is why I wanted feedback.
Thank you. I'll get to work on restructuring.

**Comment by Ki11erRabbit** [comment]
I have restructured the whole repo and simplified the qualifications of functions. I did remove some of the higher level bindings that used Koka's vectors but I feel like it makes more sense to keep the API restricted to just using BLAS types.

**Comment by TimWhiting** [comment]
Sorry for taking so long to get to this. I forgot about this one. I'll merge it for now, no reason to hold up an experimental API for extensive review. I feel like you did a good job redesigning it around directly using blas / external types. For a library like this using opaque references to C types with a good Koka API seems like a good strategy.

**Pull request merged**
